
import { WordCard } from './types';

export const INITIAL_WORDS: WordCard[] = [
  // ... (keeping some previous and adding many more)
  { word: "Buzdolabı", taboo: ["Mutfak", "Soğuk", "Yemek", "Beyaz Eşya", "Dondurucu"] },
  { word: "Güneş", taboo: ["Sıcak", "Yıldız", "Gündüz", "Sarı", "Gökyüzü"] },
  { word: "Kitap", taboo: ["Okumak", "Sayfa", "Kütüphane", "Yazar", "Roman"] },
  { word: "Bilgisayar", taboo: ["İnternet", "Ekran", "Klavye", "Fare", "Yazılım"] },
  { word: "Piyano", taboo: ["Enstrüman", "Tuş", "Müzik", "Siyah-Beyaz", "Nota"] },
  { word: "Uçak", taboo: ["Hava", "Pilot", "Kanat", "Ulaşım", "Havalimanı"] },
  { word: "Bisiklet", taboo: ["Pedal", "Tekerlek", "İki Teker", "Sürmek", "Kask"] },
  { word: "Futbol", taboo: ["Top", "Kale", "Maç", "Stadyum", "Ayak"] },
  { word: "Kahve", taboo: ["İçecek", "Sıcak", "Kafein", "Fincan", "Süt"] },
  { word: "Okul", taboo: ["Öğrenci", "Öğretmen", "Sınıf", "Eğitim", "Ders"] },
  { word: "Telefon", taboo: ["Aramak", "Akıllı", "Mobil", "Ekran", "Konuşmak"] },
  { word: "Sinema", taboo: ["Film", "Mısır", "İzlemek", "Salon", "Koltuk"] },
  { word: "Gitar", taboo: ["Tel", "Müzik", "Akor", "Enstrüman", "Çalmak"] },
  { word: "Doktor", taboo: ["Hastane", "İlaç", "Muayene", "Beyaz Önlük", "Sağlık"] },
  { word: "Araba", taboo: ["Tekerlek", "Direksiyon", "Ulaşım", "Benzin", "Motor"] },
  { word: "Deniz", taboo: ["Mavi", "Su", "Yüzmek", "Kum", "Tatil"] },
  { word: "Orman", taboo: ["Ağaç", "Yeşil", "Doğa", "Hayvan", "Oksijen"] },
  { word: "Şemsiye", taboo: ["Yağmur", "Islanmak", "Açmak", "Hava", "Güneş"] },
  { word: "Ayna", taboo: ["Bakmak", "Cam", "Yansıma", "Görüntü", "Yüz"] },
  { word: "Gözlük", taboo: ["Göz", "Cam", "Görmek", "Uzak", "Yakın"] },
  { word: "Astronot", taboo: ["Uzay", "Roket", "Ay", "Yıldız", "Kıyafet"] },
  { word: "Bale", taboo: ["Dans", "Müzik", "Kız", "Ayakkabı", "Sahne"] },
  { word: "Mıknatıs", taboo: ["Çekmek", "Demir", "Metal", "Kutup", "İtmek"] },
  { word: "Piramit", taboo: ["Mısır", "Üçgen", "Firavun", "Çöl", "Mezar"] },
  { word: "Teleskop", taboo: ["Yıldız", "Uzay", "Bakmak", "Gezegen", "Gözlem"] },
  { word: "Zürafa", taboo: ["Boyun", "Uzun", "Hayvan", "Afrika", "Benekli"] },
  { word: "Satranç", taboo: ["Oyun", "Mat", "Kale", "Şah", "Tahta"] },
  { word: "Keman", taboo: ["Enstrüman", "Müzik", "Yay", "Çalmak", "Tel"] },
  { word: "Robot", taboo: ["Metal", "Elektronik", "Makine", "Yazılım", "Gelecek"] },
  { word: "Hamak", taboo: ["Ağaç", "Uyku", "Bahçe", "Sallanmak", "İp"] },
  { word: "Pusula", taboo: ["Yön", "Kuzey", "Harita", "Güney", "İbre"] },
  { word: "Yanardağ", taboo: ["Lav", "Ateş", "Dağ", "Patlamak", "Magma"] },
  { word: "Zebra", taboo: ["Çizgili", "Hayvan", "Siyah-Beyaz", "Afrika", "At"] },
  { word: "Paraşüt", taboo: ["Atlamak", "Hava", "Uçak", "Yere İnmek", "Ekipman"] },
  { word: "Bal", taboo: ["Arı", "Tatlı", "Kahvaltı", "Çiçek", "Kovan"] },
  { word: "Klavye", taboo: ["Tuş", "Yazmak", "Bilgisayar", "Harf", "Ekran"] },
  { word: "Hapishane", taboo: ["Suçlu", "Kilit", "Demir Parmaklık", "Ceza", "Mahkum"] },
  { word: "Ambulans", taboo: ["Hasta", "Hastane", "Hızlı", "Sireni", "Doktor"] },
  { word: "Gökkuşağı", taboo: ["Yağmur", "Güneş", "Renk", "Gökyüzü", "Yedi"] },
  { word: "Kaktüs", taboo: ["Diken", "Çöl", "Bitki", "Su", "Yeşil"] },
  { word: "Mikroskop", taboo: ["Hücre", "Laboratuvar", "Bakmak", "Küçük", "Büyütmek"] },
  { word: "Liman", taboo: ["Gemi", "Deniz", "Kıyı", "Yük", "Beklemek"] },
  { word: "Deprem", taboo: ["Yer", "Sarsıntı", "Yıkım", "Afet", "Fay Hattı"] },
  { word: "Yangın", taboo: ["Ateş", "Orman", "Duman", "İtfaiye", "Söndürmek"] },
  { word: "Müze", taboo: ["Tarih", "Eser", "Gezmek", "Sergi", "Eski"] },
  { word: "Resim", taboo: ["Boya", "Tablo", "Sanat", "Fırça", "Çizmek"] },
  { word: "Heykel", taboo: ["Taş", "Mermer", "Sanat", "Sanatçı", "Şekil"] },
  { word: "Karne", taboo: ["Okul", "Not", "Dönem", "Tatil", "Öğrenci"] },
  { word: "Kütüphane", taboo: ["Kitap", "Okumak", "Sessiz", "Raf", "Çalışmak"] },
  { word: "Yumurta", taboo: ["Tavuk", "Kahvaltı", "Beyaz", "Sarısı", "Pişirmek"] },
  { word: "Limonata", taboo: ["İçecek", "Limon", "Sarı", "Şeker", "İçmek"] },
  { word: "Ahtapot", taboo: ["Deniz", "Kol", "Sekiz", "Hayvan", "Mürekkep"] },
  { word: "Penguen", taboo: ["Buz", "Kuş", "Antarktika", "Yürümek", "Siyah-Beyaz"] },
  { word: "Kutup Ayısı", taboo: ["Buz", "Beyaz", "Hayvan", "Kuzey", "Soğuk"] },
  { word: "Cüzdan", taboo: ["Para", "Kart", "Deri", "Cep", "Nakit"] },
  { word: "Merdiven", taboo: ["Çıkmak", "Basamak", "Kat", "Yüksek", "Asansör"] },
  { word: "Peynir", taboo: ["Süt", "Kahvaltı", "Sarı", "Fare", "Zeytin"] },
  { word: "Dondurma", taboo: ["Soğuk", "Külah", "Yaz", "Tatlı", "Meyveli"] },
  { word: "Fener", taboo: ["Işık", "Deniz", "Karanlık", "Gece", "Pilli"] },
  { word: "Balon", taboo: ["Hava", "Uçmak", "Renkli", "Doğum Günü", "Şişirmek"] },
  { word: "Harita", taboo: ["Yol", "Bulmak", "Ülke", "Şehir", "Kağıt"] },
  { word: "Kalem", taboo: ["Yazmak", "Kağıt", "Defter", "Kurşun", "Tükenmez"] },
  { word: "Aslan", taboo: ["Kral", "Orman", "Hayvan", "Kükremek", "Yele"] },
  { word: "Baklava", taboo: ["Tatlı", "Şerbet", "Fıstık", "Hamur", "Tepsi"] },
  { word: "Düğün", taboo: ["Evlenmek", "Gelin", "Damat", "Eğlence", "Müzik"] },
  { word: "Gelin", taboo: ["Düğün", "Beyaz", "Elbise", "Damat", "Evlenmek"] },
  { word: "Damat", taboo: ["Düğün", "Takım Elbise", "Gelin", "Evlenmek", "Erkek"] },
  { word: "Bebek", taboo: ["Çocuk", "Küçük", "Anne", "Ağlamak", "Süt"] },
  { word: "Uçurtma", taboo: ["Rüzgar", "Hava", "Uçurmak", "İp", "Kağıt"] },
  { word: "Lunapark", taboo: ["Eğlence", "Dönme Dolap", "Çarpışan Arabalar", "Bilet", "Oyun"] },
  { word: "Tiyatro", taboo: ["Sahne", "Oyuncu", "Oyun", "Perde", "İzlemek"] },
  { word: "Konser", taboo: ["Müzik", "Şarkıcı", "Sahne", "Dinlemek", "Bilet"] },
  { word: "Hamburger", taboo: ["Yemek", "Ekmek", "Köfte", "Patates", "Fast Food"] },
  { word: "Pizza", taboo: ["Yemek", "İtalyan", "Hamur", "Peynir", "Dilim"] },
  { word: "Kebap", taboo: ["Et", "Yemek", "Şiş", "Döner", "Restoran"] },
  { word: "Makarna", taboo: ["Yemek", "İtalyan", "Hamur", "Süzgeç", "Pişirmek"] },
  { word: "Pasta", taboo: ["Tatlı", "Doğum Günü", "Kek", "Krema", "Mum"] },
  { word: "Ceket", taboo: ["Giyinmek", "Kıyafet", "Düğme", "Mont", "Pantolon"] },
  { word: "Pantolon", taboo: ["Bacak", "Giyinmek", "Kemer", "Kot", "Kıyafet"] },
  { word: "Yorgan", taboo: ["Yatak", "Uyku", "Sıcak", "Kış", "Battaniye"] },
  { word: "Havlu", taboo: ["Kurulanmak", "Banyo", "Su", "Islak", "Yüz"] },
  { word: "Makas", taboo: ["Kesmek", "Kağıt", "Berber", "Keskin", "Metal"] },
  { word: "Eldiven", taboo: ["El", "Kış", "Soğuk", "Parmak", "Takmak"] },
  { word: "Atkı", taboo: ["Boyun", "Kış", "Soğuk", "Yün", "Sarmak"] },
  { word: "Mayo", taboo: ["Deniz", "Yüzmek", "Su", "Kıyafet", "Havuz"] },
  { word: "Kumsal", taboo: ["Deniz", "Kum", "Yaz", "Güneş", "Sahil"] },
  { word: "Gemi", taboo: ["Deniz", "Su", "Kaptan", "Liman", "Ulaşım"] },
  { word: "Köpek Balığı", taboo: ["Deniz", "Tehlikeli", "Diş", "Yüzmek", "Hayvan"] },
  { word: "Ambulans", taboo: ["Hasta", "Hastane", "Hızlı", "Sireni", "Doktor"] },
  { word: "Sınav", taboo: ["Okul", "Öğrenci", "Soru", "Kağıt", "Not"] },
  { word: "Üniversite", taboo: ["Okul", "Diploma", "Bölüm", "Öğrenci", "Kampüs"] },
  { word: "Radyo", taboo: ["Müzik", "Dinlemek", "Yayın", "Haber", "Ses"] },
  { word: "İnternet", taboo: ["Bilgisayar", "Web", "Bağlantı", "Ağ", "Site"] },
  { word: "E-posta", taboo: ["İnternet", "Mesaj", "Yazmak", "Adres", "Göndermek"] },
  { word: "Fotoğraf", taboo: ["Kamera", "Çekmek", "Albüm", "Resim", "Anı"] },
  { word: "Kulaklık", taboo: ["Ses", "Müzik", "Dinlemek", "Kulak", "Takmak"] },
  { word: "Fırın", taboo: ["Yemek", "Pişirmek", "Sıcak", "Mutfak", "Kek"] },
  { word: "Süzgeç", taboo: ["Su", "Makarna", "Mutfak", "Ayırmak", "Delikli"] },
  { word: "Merdane", taboo: ["Hamur", "Açmak", "Mutfak", "Börek", "Un"] },
  { word: "Baharat", taboo: ["Yemek", "Tuz", "Biber", "Tat", "Koku"] },
  { word: "Domates", taboo: ["Kırmızı", "Sebze", "Salata", "Yemek", "Yaz"] },
  { word: "Salatalık", taboo: ["Yeşil", "Sebze", "Salata", "Su", "Yaz"] },
  { word: "Karnabahar", taboo: ["Sebze", "Beyaz", "Kış", "Yemek", "Haşlama"] },
  { word: "Bezelye", taboo: ["Yeşil", "Küçük", "Sebze", "Taneli", "Yemek"] },
  { word: "Yoğurt", taboo: ["Beyaz", "Süt", "Ayran", "Yemek", "Kase"] },
  { word: "Çorba", taboo: ["Sıcak", "Kaşık", "İçmek", "Mutfak", "Yemek"] },
  { word: "Patlıcan", taboo: ["Mor", "Sebze", "Közleme", "Yemek", "Musakka"] },
  { word: "Sarışın", taboo: ["Saç", "Sarı", "Renk", "İnsan", "Kumral"] },
  { word: "Gökdelen", taboo: ["Bina", "Yüksek", "Şehir", "Kat", "Asansör"] },
  { word: "Okyanus", taboo: ["Deniz", "Su", "Büyük", "Balık", "Mavi"] },
  { word: "Çöl", taboo: ["Kum", "Sıcak", "Su", "Deve", "Güneş"] },
  { word: "Mühendis", taboo: ["İnşaat", "Makine", "Hesap", "Teknik", "Üniversite"] },
  { word: "Mimar", taboo: ["Bina", "Çizim", "Proje", "Ev", "İnşaat"] },
  { word: "Hakim", taboo: ["Mahkeme", "Adalet", "Karar", "Cübbe", "Tokmak"] },
  { word: "Berber", taboo: ["Saç", "Kesmek", "Sakal", "Makas", "Ayna"] },
  { word: "Terzi", taboo: ["Dikiş", "Kıyafet", "İğne", "Mezura", "Kumaş"] },
  { word: "Kaptan", taboo: ["Gemi", "Deniz", "Uçak", "Pilot", "Yönetmek"] },
  { word: "Dede", taboo: ["Yaşlı", "Torun", "Baba", "Aile", "Baston"] },
  { word: "Nene", taboo: ["Yaşlı", "Anne", "Torun", "Aile", "Örgü"] },
  { word: "Kuzen", taboo: ["Akraba", "Teyze", "Amca", "Aile", "Çocuk"] },
  { word: "Komşu", taboo: ["Ev", "Yan", "Oturmak", "Apartman", "Tuz İsteme"] },
  { word: "Misafir", taboo: ["Ev", "Ziyaret", "İkram", "Kapı", "Ağırlamak"] },
  { word: "Pazar", taboo: ["Hafta Sonu", "Tatil", "Alışveriş", "Sebze", "Meyve"] },
  { word: "Bayram", taboo: ["Tatil", "Şeker", "Kurban", "Ziyaret", "Eğlence"] },
  { word: "Hediye", taboo: ["Paket", "Sürpriz", "Doğum Günü", "Vermek", "Almak"] },
  { word: "Kamera", taboo: ["Video", "Çekmek", "Lens", "Fotoğraf", "Dijital"] },
  { word: "Gölge", taboo: ["Güneş", "Karanlık", "Işık", "Yansıma", "Siyah"] },
  { word: "Sır", taboo: ["Gizli", "Kimse", "Söylemek", "Saklamak", "Özel"] },
  { word: "Rüya", taboo: ["Uyku", "Gece", "Görmek", "Hayal", "Yatak"] },
  { word: "Kabus", taboo: ["Uyku", "Korku", "Gece", "Rüya", "Uyanmak"] },
  { word: "Nefes", taboo: ["Hava", "Akciğer", "Almak", "Vermek", "Burun"] },
  { word: "Kalp", taboo: ["Aşk", "Vücut", "Kan", "Atmak", "Göğüs"] },
  { word: "Beyin", taboo: ["Düşünmek", "Kafa", "Zeka", "Vücut", "Organ"] },
  { word: "Göz", taboo: ["Görmek", "Bakmak", "Yüz", "Organ", "Gözlük"] },
  { word: "Kulak", taboo: ["Duymak", "İşitmek", "Kupe", "Organ", "Ses"] },
  { word: "Dil", taboo: ["Tat", "Konuşmak", "Ağız", "Lisan", "Yabancı"] },
  { word: "El", taboo: ["Parmak", "Tutmak", "Kol", "Vücut", "Yazmak"] },
  { word: "Ayak", taboo: ["Yürümek", "Bacak", "Ayakkabı", "Vücut", "Pedal"] },
  { word: "Diz", taboo: ["Bacak", "Eklem", "Kapak", "Çökmek", "Vücut"] },
  { word: "Omuz", taboo: ["Kol", "Baş", "Vücut", "Taşımak", "Boyun"] },
  { word: "Saç", taboo: ["Kafa", "Berber", "Taramak", "Kıl", "Şampuan"] },
  { word: "Sakal", taboo: ["Erkek", "Yüz", "Kesmek", "Berber", "Bıyık"] },
  { word: "Bıyık", taboo: ["Erkek", "Dudak", "Üst", "Sakal", "Yüz"] },
  { word: "Kirpik", taboo: ["Göz", "Kapak", "Tüy", "Bakış", "Rimel"] },
  { word: "Kaş", taboo: ["Göz", "Yüz", "Tüy", "Çatmak", "İnsan"] },
  { word: "Tırnak", taboo: ["Parmak", "Kesmek", "Makas", "Oje", "Sert"] },
  { word: "Kemik", taboo: ["Vücut", "Sert", "İskelet", "Kırılmak", "Beyaz"] },
  { word: "Kan", taboo: ["Kırmızı", "Vücut", "Damar", "Akışkan", "Kalp"] },
  { word: "Damar", taboo: ["Kan", "Vücut", "İçinde", "Akış", "Mavi"] },
  { word: "Hücre", taboo: ["Biyoloji", "Canlı", "Küçük", "Mikroskop", "Vücut"] },
  { word: "Zeka", taboo: ["Akıl", "Düşünmek", "Beyin", "Problem", "Çözmek"] },
  { word: "Mantık", taboo: ["Düşünmek", "Doğru", "Akıl", "Matematik", "Felsefe"] },
  { word: "Felsefe", taboo: ["Düşünmek", "Soru", "Filozof", "Varlık", "Hayat"] },
  { word: "Din", taboo: ["İnanç", "İbadet", "Tanrı", "Cami", "Kutsal"] },
  { word: "Cami", taboo: ["İbadet", "Müslüman", "Minare", "Namaz", "Ezan"] },
  { word: "Kilise", taboo: ["İbadet", "Hristiyan", "Çan", "Papaz", "Dua"] },
  { word: "Dua", taboo: ["İstemek", "Tanrı", "İbadet", "El Açmak", "Kutsal"] },
  { word: "Cennet", taboo: ["Ölüm", "Güzel", "Tanrı", "Cehennem", "Hayat"] },
  { word: "Cehennem", taboo: ["Ölüm", "Ateş", "Tanrı", "Cennet", "Kötü"] },
  { word: "Melek", taboo: ["Kanat", "Tanrı", "Beyaz", "İyi", "Görünmez"] },
  { word: "Şeytan", taboo: ["Kötü", "Melek", "Tanrı", "Cehennem", "Günah"] },
  { word: "Günah", taboo: ["Hata", "Din", "Kötü", "Sevap", "Yasak"] },
  { word: "Sevap", taboo: ["İyi", "Din", "Günah", "Kazanmak", "Yardım"] },
  { word: "Yardım", taboo: ["Destek", "İyilik", "Etmek", "Muhtaç", "El Uzatmak"] },
  { word: "Sadaka", taboo: ["Para", "Yardım", "Din", "Fakir", "Vermek"] },
  { word: "Oruç", taboo: ["Yemek", "Ramazan", "İftar", "Sahur", "Aç Kalmak"] },
  { word: "Hac", taboo: ["Mekke", "Kabe", "Ziyaret", "Müslüman", "Din"] },
  { word: "Namaz", taboo: ["İbadet", "Cami", "Ezan", "Beş Vakit", "Secde"] },
  { word: "Ezan", taboo: ["Cami", "Namaz", "Vakit", "Okumak", "Ses"] },
  { word: "Zaman", taboo: ["Saat", "Dakika", "Akış", "Geçmiş", "Gelecek"] },
  { word: "Geçmiş", taboo: ["Zaman", "Anı", "Eski", "Dün", "Tarih"] },
  { word: "Gelecek", taboo: ["Zaman", "Yarın", "Sonra", "Plan", "Hayal"] },
  { word: "Huzur", taboo: ["Mutluluk", "Sakin", "Rahat", "İç", "Dingin"] },
  { word: "Korku", taboo: ["Endişe", "Kabus", "Karanlık", "Ürkmek", "Duygu"] },
  { word: "Sevgi", taboo: ["Aşk", "Kalp", "Değer", "Vermek", "Anne"] },
  { word: "Aşk", taboo: ["Sevgi", "Kalp", "Sevgili", "Evlilik", "Duygu"] },
  { word: "Nefret", taboo: ["Kötü", "Sevmemek", "Duygu", "Öfke", "Düşman"] },
  { word: "Öfke", taboo: ["Kızgın", "Bağırmak", "Duygu", "Sinir", "Sakin"] },
  { word: "Sabır", taboo: ["Beklemek", "Dayanmak", "Sakin", "Zaman", "Acı"] },
  { word: "Güven", taboo: ["İnanmak", "Sadakat", "Doğru", "Arkadaş", "Emin"] },
  { word: "Adalet", taboo: ["Hak", "Hukuk", "Mahkeme", "Eşitlik", "Hakim"] },
  { word: "Eşitlik", taboo: ["Aynı", "Hak", "Adalet", "İnsan", "Farklı"] },
  { word: "Özgürlük", taboo: ["Bağımsız", "Kuş", "Hapis", "Kendi", "Hak"] },
  { word: "Barış", taboo: ["Savaş", "Güvercin", "Anlaşma", "Dünya", "Huzur"] },
  { word: "Savaş", taboo: ["Asker", "Silah", "Barış", "Ülke", "Yıkım"] },
  { word: "Ülke", taboo: ["Vatan", "Bayrak", "Devlet", "Toprak", "Millet"] },
  { word: "Şehir", taboo: ["Bina", "Kalabalık", "Nüfus", "Belediye", "İl"] },
  { word: "Köy", taboo: ["Doğa", "Tarım", "Hayvan", "Muhtar", "Küçük"] },
  { word: "Mahalle", taboo: ["Sokak", "Şehir", "Ev", "Komşu", "Semt"] },
  { word: "Sokak", taboo: ["Yol", "Cadde", "Ev", "Yürümek", "Şehir"] },
  { word: "Yol", taboo: ["Araba", "Gitmek", "Sokak", "Asfalt", "Ulaşım"] },
  { word: "Trafik", taboo: ["Araba", "Kalabalık", "Lamba", "Yol", "Sıkışık"] },
  { word: "Lamba", taboo: ["Işık", "Elektrik", "Karanlık", "Gece", "Aydınlık"] },
  { word: "Göl", taboo: ["Su", "Deniz", "Tatlı", "Kara", "Balık"] },
  { word: "Nehir", taboo: ["Su", "Akarsu", "Dere", "Deniz", "Akmak"] },
  { word: "Dere", taboo: ["Su", "Küçük", "Akmak", "Nehir", "Dağ"] },
  { word: "Dağ", taboo: ["Yüksek", "Zirve", "Tırmanmak", "Kar", "Taş"] },
  { word: "Tepe", taboo: ["Dağ", "Yüksek", "Küçük", "Çıkmak", "Manzara"] },
  { word: "Vadi", taboo: ["Dağ", "Arasında", "Aşağı", "Doğa", "Yeşil"] },
  { word: "Ada", taboo: ["Kara", "Deniz", "Su", "Etrafı", "Gemi"] },
  { word: "Kıta", taboo: ["Dünya", "Büyük", "Kara", "Avrupa", "Asya"] },
  { word: "Dünya", taboo: ["Gezegen", "Yaşam", "İnsan", "Yuvarlak", "Evren"] },
  { word: "Gezegen", taboo: ["Uzay", "Dünya", "Mars", "Yıldız", "Dönmek"] },
  { word: "Yıldız", taboo: ["Gökyüzü", "Gece", "Işık", "Parlak", "Güneş"] },
  { word: "Güneş", taboo: ["Sıcak", "Işık", "Gündüz", "Sarı", "Yıldız"] },
  { word: "Ay", taboo: ["Gece", "Gökyüzü", "Işık", "Dünya", "Uydu"] },
  { word: "Evren", taboo: ["Uzay", "Her Şey", "Büyük", "Yıldız", "Sonsuz"] },
  { word: "Boşluk", taboo: ["Hiçbir Şey", "Uzay", "Doldurmak", "Hava", "Vakum"] },
  { word: "Zaman", taboo: ["Saat", "Dakika", "Saniye", "Akış", "Geçmek"] },
  { word: "Saniye", taboo: ["Dakika", "Saat", "Zaman", "Hızlı", "Tik Tak"] },
  { word: "Dakika", taboo: ["Saat", "Saniye", "Zaman", "Altmış", "Beklemek"] },
  { word: "Saat", taboo: ["Zaman", "Dakika", "Bilek", "Duvar", "Rakam"] },
  { word: "Gün", taboo: ["Zaman", "Sabah", "Akşam", "Yirmi Dört", "Hafta"] },
  { word: "Hafta", taboo: ["Gün", "Yedi", "Pazartesi", "Zaman", "Ay"] },
  { word: "Ay", taboo: ["Yıl", "Otuz", "Zaman", "Ocak", "Mevsim"] },
  { word: "Yıl", taboo: ["Zaman", "Ay", "Mevsim", "Takvim", "Yeni"] },
  { word: "Yüzyıl", taboo: ["Zaman", "Yüz Yıl", "Asır", "Tarih", "Eski"] },
  { word: "Tarih", taboo: ["Geçmiş", "Olay", "Eski", "Zaman", "Okul"] },
  { word: "Efsane", taboo: ["Hikaye", "Eski", "Masal", "İnanmak", "Gerçek Dışı"] },
  { word: "Masal", taboo: ["Çocuk", "Anlatmak", "Uyku", "Kurgu", "Prenses"] },
  { word: "Hikaye", taboo: ["Anlatmak", "Kitap", "Olay", "Yazar", "Kısa"] },
  { word: "Roman", taboo: ["Kitap", "Uzun", "Yazar", "Okumak", "Hikaye"] },
  { word: "Şiir", taboo: ["Yazmak", "Şair", "Mısra", "Kafiye", "Duygu"] },
  { word: "Şair", taboo: ["Şiir", "Yazmak", "Duygu", "Mısra", "Edebiyat"] },
  { word: "Yazar", taboo: ["Kitap", "Yazmak", "Roman", "Hikaye", "Edebiyat"] },
  { word: "Okur", taboo: ["Kitap", "Okumak", "Gazete", "Kütüphane", "Takip"] },
  { word: "Gazete", taboo: ["Haber", "Okumak", "Kağıt", "Günlük", "Manşet"] },
  { word: "Dergi", taboo: ["Okumak", "Sayfa", "Kapak", "Yazı", "Haftalık"] },
  { word: "Haber", taboo: ["Bilgi", "Olay", "Televizyon", "Gazete", "Yeni"] },
  { word: "Televizyon", taboo: ["Dizi", "İzlemek", "Ekran", "Kumanda", "Haber"] },
  { word: "Dizi", taboo: ["Televizyon", "Bölüm", "İzlemek", "Oyuncu", "Haftalık"] },
  { word: "Film", taboo: ["Sinema", "İzlemek", "Ekran", "Oyuncu", "Yönetmen"] },
  { word: "Yönetmen", taboo: ["Film", "Çekmek", "Sinema", "Oyuncu", "Kamera"] },
  { word: "Oyuncu", taboo: ["Film", "Tiyatro", "Sahne", "Rol", "Sanatçı"] },
  { word: "Sanat", taboo: ["Resim", "Müzik", "Yaratıcılık", "Güzel", "Eser"] },
  { word: "Eser", taboo: ["Sanat", "Yapmak", "Müze", "Kitap", "Tablo"] },
  { word: "Müzik", taboo: ["Dinlemek", "Ses", "Şarkı", "Nota", "Enstrüman"] },
  { word: "Şarkı", taboo: ["Müzik", "Söylemek", "Ses", "Söz", "Dinlemek"] },
  { word: "Şarkıcı", taboo: ["Müzik", "Şarkı", "Ses", "Söylemek", "Konser"] },
  { word: "Nota", taboo: ["Müzik", "Kağıt", "Porte", "Do Re Mi", "Okumak"] },
  { word: "Ritim", taboo: ["Müzik", "Tempo", "Davul", "Hız", "Vuruş"] },
  { word: "Tempo", taboo: ["Müzik", "Hız", "Ritim", "Vuruş", "Hızlı"] },
  { word: "Ses", taboo: ["Duymak", "Konuşmak", "Müzik", "Gürültü", "Kulak"] },
  { word: "Gürültü", taboo: ["Ses", "Rahatsız", "Yüksek", "Bağırmak", "Sessiz"] },
  { word: "Sessiz", taboo: ["Ses Yok", "Huzur", "Kütüphane", "Gece", "Konuşmamak"] },
  { word: "Işık", taboo: ["Aydınlık", "Lamba", "Güneş", "Karanlık", "Görmek"] },
  { word: "Karanlık", taboo: ["Işık Yok", "Gece", "Siyah", "Korku", "Görmemek"] },
  { word: "Renk", taboo: ["Kırmızı", "Mavi", "Boya", "Görmek", "Gökkuşağı"] },
  { word: "Siyah", taboo: ["Renk", "Karanlık", "Beyaz", "Gece", "Koyu"] },
  { word: "Beyaz", taboo: ["Renk", "Siyah", "Kar", "Süt", "Açık"] },
  { word: "Kırmızı", taboo: ["Renk", "Kan", "Elma", "Bayrak", "Ateş"] },
  { word: "Mavi", taboo: ["Renk", "Deniz", "Gökyüzü", "Su", "Açık"] },
  { word: "Yeşil", taboo: ["Renk", "Ağaç", "Doğa", "Yaprak", "Çimen"] },
  { word: "Sarı", taboo: ["Renk", "Güneş", "Limon", "Altın", "Parlak"] },
  { word: "Turuncu", taboo: ["Renk", "Portakal", "Kırmızı", "Sarı", "Meyve"] },
  { word: "Mor", taboo: ["Renk", "Patlıcan", "Üzüm", "Kırmızı", "Mavi"] },
  { word: "Pembe", taboo: ["Renk", "Kız", "Gül", "Açık Kırmızı", "Flamingo"] },
  { word: "Kahverengi", taboo: ["Renk", "Toprak", "Ağaç", "Çikolata", "Koyu"] },
  { word: "Gri", taboo: ["Renk", "Siyah", "Beyaz", "Bulut", "Metal"] },
  { word: "Altın", taboo: ["Metal", "Sarı", "Değerli", "Takı", "Para"] },
  { word: "Gümüş", taboo: ["Metal", "Gri", "Değerli", "Takı", "Parlak"] },
  { word: "Bakır", taboo: ["Metal", "Kızıl", "Tencere", "Tel", "İletken"] },
  { word: "Demir", taboo: ["Metal", "Sert", "İnşaat", "Mıknatıs", "Çelik"] },
  { word: "Çelik", taboo: ["Metal", "Sert", "Demir", "Tencere", "Sağlam"] },
  { word: "Plastik", taboo: ["Malzeme", "Poşet", "Şişe", "Geri Dönüşüm", "Yapay"] },
  { word: "Cam", taboo: ["Pencere", "Kırılmak", "Şeffaf", "Bardak", "Ayna"] },
  { word: "Kağıt", taboo: ["Yazmak", "Kitap", "Defter", "Ağaç", "Beyaz"] },
  { word: "Kumaş", taboo: ["Kıyafet", "Dikmek", "Pamuk", "İpek", "Tekstil"] },
  { word: "Pamuk", taboo: ["Kumaş", "Yumuşak", "Beyaz", "Tarla", "Bitki"] },
  { word: "İpek", taboo: ["Kumaş", "Böcek", "Yumuşak", "Değerli", "Parlak"] },
  { word: "Yün", taboo: ["Kumaş", "Koyun", "Sıcak", "Kazak", "Kış"] },
  { word: "Deri", taboo: ["Vücut", "Hayvan", "Ceket", "Ayakkabı", "Malzeme"] },
  { word: "Tahta", taboo: ["Ağaç", "Masa", "Mobilya", "Odun", "Malzeme"] },
  { word: "Taş", taboo: ["Sert", "Doğa", "Kaya", "Duvar", "Yer"] },
  { word: "Kum", taboo: ["Plaj", "Çöl", "Küçük", "Taş", "Deniz"] },
  { word: "Toprak", taboo: ["Bitki", "Yer", "Tarım", "Çamur", "Kahverengi"] },
  { word: "Çamur", taboo: ["Toprak", "Su", "Islak", "Kirli", "Yağmur"] },
  { word: "Toz", taboo: ["Kir", "Küçük", "Temizlemek", "Hava", "Yer"] },
  { word: "Kir", taboo: ["Pis", "Yıkamak", "Leke", "Temizlemek", "Toz"] },
  { word: "Pis", taboo: ["Kirli", "Kötü", "Temiz", "Koku", "Yıkamak"] },
  { word: "Temiz", taboo: ["Kirli Değil", "Yıkamak", "Güzel", "Sabun", "Pak"] },
  { word: "Hava", taboo: ["Nefes", "Gökyüzü", "Görünmez", "Oksijen", "Rüzgar"] },
  { word: "Su", taboo: ["İçmek", "Sıvı", "Deniz", "Yaşam", "Bardak"] },
  { word: "Ateş", taboo: ["Sıcak", "Yakmak", "Duman", "Kırmızı", "Odun"] },
  { word: "Buz", taboo: ["Su", "Soğuk", "Donmak", "Kış", "Dondurucu"] },
  { word: "Buhar", taboo: ["Su", "Sıcak", "Gaz", "Bulut", "Uçmak"] },
  { word: "Gaz", taboo: ["Hava", "Buhar", "Mutfak", "Ocak", "Uçucu"] },
  { word: "Sıvı", taboo: ["Su", "Akışkan", "İçecek", "Yağ", "Madde"] },
  { word: "Katı", taboo: ["Sert", "Taş", "Madde", "Sıvı", "Şekil"] },
  { word: "Sert", taboo: ["Yumuşak Değil", "Taş", "Demir", "Katı", "Kuvvet"] },
  { word: "Yumuşak", taboo: ["Sert Değil", "Pamuk", "Yastık", "Kumaş", "Hafif"] },
  { word: "Ağır", taboo: ["Hafif Değil", "Taşımak", "Kilo", "Büyük", "Zor"] },
  { word: "Hafif", taboo: ["Ağır Değil", "Pamuk", "Tüy", "Kolay", "Az"] },
  { word: "Hızlı", taboo: ["Yavaş Değil", "Koşmak", "Araba", "Sürat", "Çabuk"] },
  { word: "Yavaş", taboo: ["Hızlı Değil", "Kaplumbağa", "Yürümek", "Sakin", "Az"] },
  { word: "Sıcak", taboo: ["Soğuk Değil", "Güneş", "Ateş", "Yaz", "Isı"] },
  { word: "Soğuk", taboo: ["Sıcak Değil", "Buz", "Kar", "Kış", "Dondurucu"] },
  { word: "Ilık", taboo: ["Sıcak", "Soğuk", "Su", "Hava", "Orta"] },
  { word: "Büyük", taboo: ["Küçük Değil", "Dev", "Geniş", "Çok", "Fazla"] },
  { word: "Küçük", taboo: ["Büyük Değil", "Az", "Dar", "Mini", "Kısa"] },
  { word: "Uzun", taboo: ["Kısa Değil", "Boy", "Yol", "Zaman", "Fazla"] },
  { word: "Kısa", taboo: ["Uzun Değil", "Boy", "Zaman", "Az", "Küçük"] },
  { word: "Geniş", taboo: ["Dar Değil", "Büyük", "Yol", "Masa", "Alan"] },
  { word: "Dar", taboo: ["Geniş Değil", "Küçük", "Sokak", "Kıyafet", "Sıkışık"] },
  { word: "Yüksek", taboo: ["Alçak Değil", "Dağ", "Bina", "Yukarı", "Tepe"] },
  { word: "Alçak", taboo: ["Yüksek Değil", "Aşağı", "Yer", "Kısa", "Seviye"] },
  { word: "Derin", taboo: ["Sığ Değil", "Deniz", "Kuyu", "Su", "Aşağı"] },
  { word: "Sığ", taboo: ["Derin Değil", "Deniz", "Su", "Kenar", "Kısa"] },
  { word: "Yeni", taboo: ["Eski Değil", "Taze", "Satın Almak", "Modern", "Gelecek"] },
  { word: "Eski", taboo: ["Yeni Değil", "Tarih", "Geçmiş", "Yıpranmış", "Antika"] },
  { word: "Taze", taboo: ["Bayat Değil", "Yeni", "Yemek", "Ekmek", "Meyve"] },
  { word: "Bayat", taboo: ["Taze Değil", "Eski", "Ekmek", "Yemek", "Sert"] },
  { word: "Tatlı", taboo: ["Şeker", "Acı Değil", "Pasta", "Bal", "Güzel"] },
  { word: "Acı", taboo: ["Biber", "Tatlı Değil", "Yemek", "Can Yakmak", "Kötü"] },
  { word: "Ekşi", taboo: ["Limon", "Yoğurt", "Tat", "Yüz Buruşturmak", "Meyve"] },
  { word: "Tuzlu", taboo: ["Tuz", "Yemek", "Deniz", "Tad", "Beyaz"] },
  { word: "Zengin", taboo: ["Para", "Çok", "Fakir Değil", "Varlıklı", "Lüks"] },
  { word: "Fakir", taboo: ["Para", "Az", "Zengin Değil", "Muhtaç", "Yardım"] },
  { word: "Mutlu", taboo: ["Üzgün Değil", "Gülmek", "Sevinç", "Huzur", "Duygu"] },
  { word: "Üzgün", taboo: ["Mutlu Değil", "Ağlamak", "Keder", "Kötü", "Duygu"] },
  { word: "Ağlamak", taboo: ["Gözyaşı", "Üzgün", "Mutsuz", "Göz", "Duygu"] },
  { word: "Gülmek", taboo: ["Mutlu", "Eğlence", "Kahkaha", "Ağız", "Komik"] },
  { word: "Komik", taboo: ["Gülmek", "Şaka", "Eğlence", "Koray", "Palyaço"] },
  { word: "Şaka", taboo: ["Komik", "Gülmek", "Eğlence", "Yapmak", "Ciddi Değil"] },
  { word: "Ciddi", taboo: ["Şaka Değil", "Sert", "Önemli", "Resmi", "Ağır"] },
  { word: "Zor", taboo: ["Kolay Değil", "Problem", "Çözmek", "Sıkıntı", "Zahmet"] },
  { word: "Kolay", taboo: ["Zor Değil", "Basit", "Rahat", "Çabuk", "Hemen"] },
  { word: "Basit", taboo: ["Kolay", "Zor Değil", "Karışık Değil", "Yalın", "Sade"] },
  { word: "Karışık", taboo: ["Zor", "Basit Değil", "Düzensiz", "Çok", "Farklı"] },
  { word: "Düzenli", taboo: ["Karışık Değil", "Tertipli", "Güzel", "Sıralı", "Yerli Yerinde"] },
  { word: "Düzensiz", taboo: ["Düzenli Değil", "Karışık", "Dağınık", "Kötü", "Heryerde"] },
  { word: "Doğru", taboo: ["Yanlış Değil", "Gerçek", "Yalan Değil", "Dürüst", "Haklı"] },
  { word: "Yanlış", taboo: ["Doğru Değil", "Hata", "Yalan", "Kötü", "Düzeltmek"] },
  { word: "Hata", taboo: ["Yanlış", "Yapmak", "Düzeltmek", "Özür", "Kötü"] },
  { word: "Özür", taboo: ["Hata", "Dilemek", "Yanlış", "Pişman", "Affetmek"] },
  { word: "Pişman", taboo: ["Hata", "Özür", "Üzgün", "Keşke", "Duygu"] },
  { word: "Affetmek", taboo: ["Özür", "Hata", "Kabul", "Barış", "Unutmak"] },
  { word: "Yalan", taboo: ["Doğru Değil", "Gerçek Değil", "Söylemek", "Kandırmak", "Kötü"] },
  { word: "Gerçek", taboo: ["Yalan Değil", "Doğru", "Hayal Değil", "Var", "Olan"] },
  { word: "Hayal", taboo: ["Gerçek Değil", "Rüya", "Düşünmek", "Gelecek", "Umut"] },
  { word: "Umut", taboo: ["Hayal", "Beklemek", "İyi", "Gelecek", "İnanmak"] },
  { word: "Şans", taboo: ["Talih", "Kader", "İyi", "Piyango", "Kazanmak"] },
  { word: "Kader", taboo: ["Şans", "Alın Yazısı", "Gelecek", "Tanrı", "Hayat"] },
  { word: "Ölüm", taboo: ["Hayat Sonu", "Mezar", "Cenaze", "Yaşam Değil", "Son"] },
  { word: "Yaşam", taboo: ["Hayat", "Canlı", "Ölüm Değil", "Dünya", "Nefes"] },
  { word: "Doğum", taboo: ["Bebek", "Başlangıç", "Hayat", "Anne", "Hastane"] },
  { word: "Büyümek", taboo: ["Çocuk", "Yaşlanmak", "Gelişmek", "Boy", "Zaman"] },
  { word: "Yaşlanmak", taboo: ["Dede", "Nene", "Zaman", "Eski", "Büyümek"] },
  { word: "Sağlık", taboo: ["Doktor", "Hasta Değil", "İyi", "Vücut", "Yaşam"] },
  { word: "Hasta", taboo: ["Doktor", "İlaç", "Yatak", "Kötü", "Sağlık Değil"] },
  { word: "İlaç", taboo: ["Doktor", "Hasta", "Eczane", "İçmek", "İyileşmek"] },
  { word: "Eczane", taboo: ["İlaç", "Satmak", "Hasta", "Doktor", "Dükkan"] },
  { word: "Hastane", taboo: ["Doktor", "Hasta", "Hemşire", "Bina", "Ameliyat"] },
  { word: "Hemşire", taboo: ["Hastane", "Doktor", "Yardım", "Hasta", "Beyaz"] },
  { word: "Ameliyat", taboo: ["Hastane", "Doktor", "Kesmek", "Hasta", "Masa"] },
  { word: "Kaza", taboo: ["Araba", "Kötü", "Olay", "Yaralanmak", "Hata"] },
  { word: "Yaralanmak", taboo: ["Kaza", "Acı", "Kan", "Doktor", "Vücut"] },
  { word: "Tehlike", taboo: ["Korku", "Dikkat", "Kötü", "Risk", "Güvenli Değil"] },
  { word: "Güvenli", taboo: ["Tehlike Değil", "Emin", "Rahat", "Korkusuz", "Koruma"] },
  { word: "Koruma", taboo: ["Güvenlik", "Polis", "Bekçi", "Kollamak", "Zırh"] },
  { word: "Zırh", taboo: ["Koruma", "Sert", "Metal", "Savaş", "Asker"] },
  { word: "Silah", taboo: ["Savaş", "Asker", "Ateş", "Tabanca", "Kötü"] },
  { word: "Tabanca", taboo: ["Silah", "Ateş", "Mermi", "Polis", "Asker"] },
  { word: "Mermi", taboo: ["Silah", "Tabanca", "Ateş", "Küçük", "Metal"] },
  { word: "Bıçak", taboo: ["Kesmek", "Keskin", "Mutfak", "Silah", "Metal"] },
  { word: "Keskin", taboo: ["Bıçak", "Makas", "Kesmek", "Acı", "Sivri"] },
  { word: "Sivri", taboo: ["İğne", "Keskin", "Uç", "Acı", "Batmak"] },
  { word: "Batmak", taboo: ["İğne", "Diken", "Acı", "Girmek", "Deniz"] },
  { word: "Diken", taboo: ["Gül", "Kaktüs", "Batmak", "Acı", "Bitki"] },
  { word: "Bitki", taboo: ["Çiçek", "Ağaç", "Yeşil", "Toprak", "Doğa"] },
  { word: "Çiçek", taboo: ["Bitki", "Gül", "Güzel", "Koku", "Renkli"] },
  { word: "Ağaç", taboo: ["Bitki", "Orman", "Dal", "Yaprak", "Büyük"] },
  { word: "Dal", taboo: ["Ağaç", "Yaprak", "Kuş", "Kırılmak", "Bitki"] },
  { word: "Yaprak", taboo: ["Ağaç", "Yeşil", "Dökülmek", "Sonbahar", "Bitki"] },
  { word: "Meyve", taboo: ["Yemek", "Tatlı", "Ağaç", "Elma", "Muz"] },
  { word: "Sebze", taboo: ["Yemek", "Toprak", "Domates", "Ispanak", "Yemek"] },
  { word: "Tarım", taboo: ["Toprak", "Bitki", "Çiftçi", "Yemek", "Tarlada"] },
  { word: "Çiftçi", taboo: ["Tarım", "Toprak", "Köy", "Ekmek", "Hayvan"] },
  { word: "Tarla", taboo: ["Toprak", "Tarım", "Bitki", "Çiftçi", "Büyük"] },
  { word: "Bahçe", taboo: ["Ev", "Ağaç", "Çiçek", "Oynamak", "Dışarı"] },
  { word: "Park", taboo: ["Oyun", "Çocuk", "Ağaç", "Bank", "Eğlence"] },
  { word: "Bank", taboo: ["Oturmak", "Park", "Tahta", "Sokak", "Dinlenmek"] },
  { word: "Koltuk", taboo: ["Ev", "Oturmak", "Yumuşak", "Mobilya", "Salon"] },
  { word: "Sandalye", taboo: ["Oturmak", "Masa", "Tahta", "Mobilya", "Dört Ayak"] },
  { word: "Mobilya", taboo: ["Masa", "Koltuk", "Ev", "Tahta", "Eşya"] },
  { word: "Eşya", taboo: ["Nesne", "Ev", "Kullanmak", "Mobilya", "Araç"] },
  { word: "Araç", taboo: ["Araba", "Ulaşım", "Kullanmak", "Gereç", "Alet"] },
  { word: "Alet", taboo: ["Araç", "Tamir", "Kullanmak", "Çekiç", "Tornavida"] },
  { word: "Tamir", taboo: ["Düzeltmek", "Bozuk", "Alet", "Usta", "Yapmak"] },
  { word: "Usta", taboo: ["Tamir", "Bilen", "İş", "Öğretmek", "Çırak"] },
  { word: "Çırak", taboo: ["Öğrenmek", "Usta", "İş", "Genç", "Yardım"] },
  { word: "İş", taboo: ["Çalışmak", "Para", "Ofis", "Meslek", "Yorgun"] },
  { word: "Meslek", taboo: ["İş", "Doktor", "Öğretmen", "Yapmak", "Para"] },
  { word: "Çalışmak", taboo: ["İş", "Yorulmak", "Para", "Okul", "Ders"] },
  { word: "Yorulmak", taboo: ["Çalışmak", "Dinlenmek", "Uyku", "Bitkin", "Çok"] },
  { word: "Dinlenmek", taboo: ["Yorulmak", "Oturmak", "Uyku", "Tatil", "Rahat"] },
  { word: "Tatil", taboo: ["Dinlenmek", "Okul Yok", "Deniz", "Yaz", "Gezmek"] },
  { word: "Gezmek", taboo: ["Tatil", "Yürümek", "Yeni Yerler", "Seyahat", "Eğlence"] },
  { word: "Seyahat", taboo: ["Gitmek", "Yolculuk", "Tatil", "Uçak", "Bavul"] },
  { word: "Bavul", taboo: ["Seyahat", "Tatil", "Eşya", "Çanta", "Yolculuk"] },
  { word: "Çanta", taboo: ["Taşımak", "Okul", "Eşya", "Kol", "Sırt"] },
  { word: "Cüzdan", taboo: ["Para", "Kart", "Çanta", "Cep", "Deri"] },
  { word: "Para", taboo: ["Satın Almak", "Zengin", "Cüzdan", "Banka", "Kağıt"] },
  { word: "Banka", taboo: ["Para", "Yatırmak", "Çekmek", "Kredi", "Kart"] },
  { word: "Kredi", taboo: ["Banka", "Para", "Borç", "Kart", "Ödemek"] },
  { word: "Borç", taboo: ["Para", "Vermek", "Almak", "Ödemek", "Banka"] },
  { word: "Fiyat", taboo: ["Para", "Değer", "Etiket", "Satın Almak", "Pahalı"] },
  { word: "Pahalı", taboo: ["Fiyat", "Çok", "Para", "Ucuz Değil", "Lüks"] },
  { word: "Ucuz", taboo: ["Fiyat", "Az", "Para", "Pahalı Değil", "İndirim"] },
  { word: "İndirim", taboo: ["Fiyat", "Ucuz", "Kampanya", "Mağaza", "Azalmak"] },
  { word: "Mağaza", taboo: ["Alışveriş", "Satmak", "Dükkan", "Kıyafet", "Bina"] },
  { word: "Alışveriş", taboo: ["Mağaza", "Para", "Almak", "Market", "Sepet"] },
  { word: "Market", taboo: ["Alışveriş", "Yemek", "Süpermarket", "Sepet", "Bakkal"] },
  { word: "Bakkal", taboo: ["Küçük", "Market", "Ekmek", "Mahalle", "Amca"] },
  { word: "Sepet", taboo: ["Taşımak", "Market", "Alışveriş", "El", "İçine Koymak"] },
  { word: "Poşet", taboo: ["Taşımak", "Plastik", "Market", "Alışveriş", "İnce"] },
  { word: "Kutu", taboo: ["İçine Koymak", "Karton", "Kapak", "Kare", "Eşya"] },
  { word: "Karton", taboo: ["Kağıt", "Sert", "Kutu", "Kalın", "Malzeme"] },
  { word: "Kare", taboo: ["Şekil", "Dört", "Kenar", "Kutu", "Geometri"] },
  { word: "Daire", taboo: ["Şekil", "Yuvarlak", "Çizgi", "Top", "Geometri"] },
  { word: "Üçgen", taboo: ["Şekil", "Üç", "Kenar", "Piramit", "Geometri"] },
  { word: "Dikdörtgen", taboo: ["Şekil", "Dört", "Kenar", "Masa", "Geometri"] },
  { word: "Çizgi", taboo: ["Kağıt", "Kalem", "Düz", "Çizmek", "Yol"] },
  { word: "Düz", taboo: ["Çizgi", "Eğri Değil", "Yol", "Zemin", "Sade"] },
  { word: "Eğri", taboo: ["Düz Değil", "Çizgi", "Yamuk", "Yol", "Dönemeç"] },
  { word: "Nokta", taboo: ["Küçük", "Kalem", "Son", "Cümle", "İşaret"] },
  { word: "Soru", taboo: ["Cevap", "Sormak", "Okul", "Sınav", "İşaret"] },
  { word: "Cevap", taboo: ["Soru", "Söylemek", "Doğru", "Bilmek", "Anlatmak"] },
  { word: "Bilmek", taboo: ["Zeka", "Akıl", "Öğrenmek", "Doğru", "Anlamak"] },
  { word: "Anlamak", taboo: ["Bilmek", "Zeka", "Akıl", "Kavramak", "Soru"] },
  { word: "Öğrenmek", taboo: ["Okul", "Öğrenci", "Ders", "Bilmek", "Yeni"] },
  { word: "Öğretmek", taboo: ["Öğretmen", "Okul", "Anlatmak", "Ders", "Bilgi"] },
  { word: "Bilgi", taboo: ["Öğrenmek", "Kitap", "Yeni", "Zeka", "İnternet"] },
  { word: "Zeka", taboo: ["Akıl", "Düşünmek", "Beyin", "Problem", "Yüksek"] }
];
